name: build-rpms
run-name: Build RPMs for various Fedora and Debian.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
    steps:
      - name: Grab the source from Git
        uses: actions/checkout@v4.1.1
      - name: Install build tooling
        run: >-
          dnf install
          --assumeyes
          dnf-plugins-core
          rpm-build
          rpmdevtools
      - name: Create rpmbuild directory structure on a community distro
        run: rpmdev-setuptree
      - name: Display directory view
        run: ls
      - name: Fetch sources and patches on a community distro
        run: >-
          spectool --all --get-files --sourcedir
          packaging/tt-topology.spec
      - name: Install static build requirements
        run: dnf builddep --assumeyes --spec packaging/tt-topology.spec
      - name: Build RPM on Fedora
        run: |
          rpmbuild -br packaging/tt-topology.spec
