name: build-rpms
run-name: Build RPMs for various Fedora and Debian.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
    steps:
      - name: Grab the source from Git
        uses: actions/checkout@v4.1.1
      - name: Run build script
        run: ./packaging/build-rpms.sh

