name: build-rpms
run-name: Build RPMs for various Fedora and Debian.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
    steps:
      - name: Install static build requirements
        run: dnf builddep --assumeyes --spec packaging/tt-topology.spec
      - name: Fetch sources and patches on a community distro
        run: >-
          spectool --all --get-files --sourcedir
          packaging/tt-topology.spec
      - name: Build RPM on Fedora
        run: |
          rpmbuild -br packaging/tt-topology.spec
